create table if not exists counter_party_exclusion_line_items(
line_item_code Integer not null,
conter_party_exclusion_ref varchar(255) null,
exclusion_valid char null,
excluded_rule_content_code Integer null,
excluded_rule_content varchar(255) null,
metadata varchar(255) null,
key_identifier Integer null,
secret_code Integer null,
key_rotation_client varchar(255) null,
line_item_reference Integer null,
key_rotation_schedule varchar(255) null,
status varchar(255) null,
remarks varchar(255) null,
constraint counter_party_exclusion_line_items_pk primary key(line_item_code));